name: Build DevContainer

on:
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**/*
      - .github/workflows/devcontainer.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Build DevContainer
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: false
          tags: ${{ github.repository }}:devcontainer
